micronaut:
  application:
    name: id-generator
    minimumAvailableIdCount: 1000
    batchSize: 100
    cacheSize: 100
    instance:
      id: ${random.uuid}
---

postgres:
  url: jdbc:postgresql://127.0.0.1:5432/id-db
  user: postgres
  password: postgres
  schemaName: id-schema
  databaseName: id-db
